/* ----------------------------------------------------------------------------------------------------------------------
* © Copyright 2018 Visa. All Rights Reserved.
*
* NOTICE: The software and accompanying information and documentation (together, the “Software”) remain the property of
* and are proprietary to Visa and its suppliers and affiliates. The Software remains protected by intellectual property
* rights and may be covered by U.S. and foreign patents or patent applications. The Software is licensed and not sold.
*
* By accessing the Software you are agreeing to Visa's terms of use (developer.visa.com/terms) and privacy policy
* (developer.visa.com/privacy). In addition, all permissible uses of the Software must be in support of Visa products,
* programs and services provided through the Visa Developer Program (VDP) platform only (developer.visa.com).
* THE SOFTWARE AND ANY ASSOCIATED INFORMATION OR DOCUMENTATION IS PROVIDED ON AN “AS IS,” “AS AVAILABLE,” “WITH ALL
* FAULTS” BASIS WITHOUT WARRANTY OR CONDITION OF ANY KIND. YOUR USE IS AT YOUR OWN RISK.
---------------------------------------------------------------------------------------------------------------------- */

/*
 * Merchant Locator API
 * Find Visa accepting merchants around by geolocation
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.hackathonteam404.project404.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * ResponseValues
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.java.JavaClientCodegen", date = "2018-12-19T10:49:03.812+05:30[Asia/Kolkata]")
public class ResponseValues {

  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("locationAddressLatitude")
  private String locationAddressLatitude = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("merchantCity")
  private String merchantCity = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("merchantStreetAddress")
  private String merchantStreetAddress = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("merchantCategoryCode")
  private List<String> merchantCategoryCode = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("distance")
  private Integer distance = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("visaEnterpriseName")
  private String visaEnterpriseName = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("businessLegalName")
  private List<String> businessLegalName = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("visaStoreName")
  private String visaStoreName = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("visaMerchantId")
  private Integer visaMerchantId = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("merchantCategoryCodeDesc")
  private List<String> merchantCategoryCodeDesc = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("merchantState")
  private String merchantState = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("visaMerchantName")
  private String visaMerchantName = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("merchantCountryCode")
  private Integer merchantCountryCode = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("merchantPostalCode")
  private String merchantPostalCode = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("dbaname")
  private List<String> dbaname = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("visaStoreId")
  private Integer visaStoreId = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("paymentFacilitatorName")
  private List<String> paymentFacilitatorName = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("merchantUrl")
  private List<String> merchantUrl = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("locationAddressLongitude")
  private String locationAddressLongitude = null;
  
  public ResponseValues locationAddressLatitude(String locationAddressLatitude) {
    this.locationAddressLatitude = locationAddressLatitude;
    return this;
  }

  
  /**
  * Merchant&amp;apos;s Location Address Latitude
  * @return locationAddressLatitude
  **/
  @ApiModelProperty(value = "Merchant&apos;s Location Address Latitude")
  public String getLocationAddressLatitude() {
    return locationAddressLatitude;
  }
  public void setLocationAddressLatitude(String locationAddressLatitude) {
    this.locationAddressLatitude = locationAddressLatitude;
  }
  
  public ResponseValues merchantCity(String merchantCity) {
    this.merchantCity = merchantCity;
    return this;
  }

  
  /**
  * City of the Merchant
  * @return merchantCity
  **/
  @ApiModelProperty(value = "City of the Merchant")
  public String getMerchantCity() {
    return merchantCity;
  }
  public void setMerchantCity(String merchantCity) {
    this.merchantCity = merchantCity;
  }
  
  public ResponseValues merchantStreetAddress(String merchantStreetAddress) {
    this.merchantStreetAddress = merchantStreetAddress;
    return this;
  }

  
  /**
  * Street Address of the Merchant
  * @return merchantStreetAddress
  **/
  @ApiModelProperty(value = "Street Address of the Merchant")
  public String getMerchantStreetAddress() {
    return merchantStreetAddress;
  }
  public void setMerchantStreetAddress(String merchantStreetAddress) {
    this.merchantStreetAddress = merchantStreetAddress;
  }
  
  public ResponseValues merchantCategoryCode(List<String> merchantCategoryCode) {
    this.merchantCategoryCode = merchantCategoryCode;
    return this;
  }

  public ResponseValues addMerchantCategoryCodeItem(String merchantCategoryCodeItem) {
    
    if (this.merchantCategoryCode == null) {
      this.merchantCategoryCode = new ArrayList<String>();
    }
    
    this.merchantCategoryCode.add(merchantCategoryCodeItem);
    return this;
  }
  
  /**
  * Category Codes of the Merchant
  * @return merchantCategoryCode
  **/
  @ApiModelProperty(value = "Category Codes of the Merchant")
  public List<String> getMerchantCategoryCode() {
    return merchantCategoryCode;
  }
  public void setMerchantCategoryCode(List<String> merchantCategoryCode) {
    this.merchantCategoryCode = merchantCategoryCode;
  }
  
  public ResponseValues distance(Integer distance) {
    this.distance = distance;
    return this;
  }

  
  /**
  * Distance of the Merchant in KM/M
  * @return distance
  **/
  @ApiModelProperty(value = "Distance of the Merchant in KM/M")
  public Integer getDistance() {
    return distance;
  }
  public void setDistance(Integer distance) {
    this.distance = distance;
  }
  
  public ResponseValues visaEnterpriseName(String visaEnterpriseName) {
    this.visaEnterpriseName = visaEnterpriseName;
    return this;
  }

  
  /**
  * Visa Enterprise Name
  * @return visaEnterpriseName
  **/
  @ApiModelProperty(value = "Visa Enterprise Name")
  public String getVisaEnterpriseName() {
    return visaEnterpriseName;
  }
  public void setVisaEnterpriseName(String visaEnterpriseName) {
    this.visaEnterpriseName = visaEnterpriseName;
  }
  
  public ResponseValues businessLegalName(List<String> businessLegalName) {
    this.businessLegalName = businessLegalName;
    return this;
  }

  public ResponseValues addBusinessLegalNameItem(String businessLegalNameItem) {
    
    if (this.businessLegalName == null) {
      this.businessLegalName = new ArrayList<String>();
    }
    
    this.businessLegalName.add(businessLegalNameItem);
    return this;
  }
  
  /**
  * Business Legal Name
  * @return businessLegalName
  **/
  @ApiModelProperty(value = "Business Legal Name")
  public List<String> getBusinessLegalName() {
    return businessLegalName;
  }
  public void setBusinessLegalName(List<String> businessLegalName) {
    this.businessLegalName = businessLegalName;
  }
  
  public ResponseValues visaStoreName(String visaStoreName) {
    this.visaStoreName = visaStoreName;
    return this;
  }

  
  /**
  * Visa Store Name for a Branch/Outlet
  * @return visaStoreName
  **/
  @ApiModelProperty(value = "Visa Store Name for a Branch/Outlet")
  public String getVisaStoreName() {
    return visaStoreName;
  }
  public void setVisaStoreName(String visaStoreName) {
    this.visaStoreName = visaStoreName;
  }
  
  public ResponseValues visaMerchantId(Integer visaMerchantId) {
    this.visaMerchantId = visaMerchantId;
    return this;
  }

  
  /**
  * Unique identifier for a Merchant provided by VISA
  * @return visaMerchantId
  **/
  @ApiModelProperty(value = "Unique identifier for a Merchant provided by VISA")
  public Integer getVisaMerchantId() {
    return visaMerchantId;
  }
  public void setVisaMerchantId(Integer visaMerchantId) {
    this.visaMerchantId = visaMerchantId;
  }
  
  public ResponseValues merchantCategoryCodeDesc(List<String> merchantCategoryCodeDesc) {
    this.merchantCategoryCodeDesc = merchantCategoryCodeDesc;
    return this;
  }

  public ResponseValues addMerchantCategoryCodeDescItem(String merchantCategoryCodeDescItem) {
    
    if (this.merchantCategoryCodeDesc == null) {
      this.merchantCategoryCodeDesc = new ArrayList<String>();
    }
    
    this.merchantCategoryCodeDesc.add(merchantCategoryCodeDescItem);
    return this;
  }
  
  /**
  * Description of the MerchantCategoryCode
  * @return merchantCategoryCodeDesc
  **/
  @ApiModelProperty(value = "Description of the MerchantCategoryCode")
  public List<String> getMerchantCategoryCodeDesc() {
    return merchantCategoryCodeDesc;
  }
  public void setMerchantCategoryCodeDesc(List<String> merchantCategoryCodeDesc) {
    this.merchantCategoryCodeDesc = merchantCategoryCodeDesc;
  }
  
  public ResponseValues merchantState(String merchantState) {
    this.merchantState = merchantState;
    return this;
  }

  
  /**
  * State of the Merchant
  * @return merchantState
  **/
  @ApiModelProperty(value = "State of the Merchant")
  public String getMerchantState() {
    return merchantState;
  }
  public void setMerchantState(String merchantState) {
    this.merchantState = merchantState;
  }
  
  public ResponseValues visaMerchantName(String visaMerchantName) {
    this.visaMerchantName = visaMerchantName;
    return this;
  }

  
  /**
  * Name of the Merchant
  * @return visaMerchantName
  **/
  @ApiModelProperty(value = "Name of the Merchant")
  public String getVisaMerchantName() {
    return visaMerchantName;
  }
  public void setVisaMerchantName(String visaMerchantName) {
    this.visaMerchantName = visaMerchantName;
  }
  
  public ResponseValues merchantCountryCode(Integer merchantCountryCode) {
    this.merchantCountryCode = merchantCountryCode;
    return this;
  }

  
  /**
  * Country Code of the Merchant
  * @return merchantCountryCode
  **/
  @ApiModelProperty(value = "Country Code of the Merchant")
  public Integer getMerchantCountryCode() {
    return merchantCountryCode;
  }
  public void setMerchantCountryCode(Integer merchantCountryCode) {
    this.merchantCountryCode = merchantCountryCode;
  }
  
  public ResponseValues merchantPostalCode(String merchantPostalCode) {
    this.merchantPostalCode = merchantPostalCode;
    return this;
  }

  
  /**
  * Postal Code of the Merchant
  * @return merchantPostalCode
  **/
  @ApiModelProperty(value = "Postal Code of the Merchant")
  public String getMerchantPostalCode() {
    return merchantPostalCode;
  }
  public void setMerchantPostalCode(String merchantPostalCode) {
    this.merchantPostalCode = merchantPostalCode;
  }
  
  public ResponseValues dbaname(List<String> dbaname) {
    this.dbaname = dbaname;
    return this;
  }

  public ResponseValues addDbanameItem(String dbanameItem) {
    
    if (this.dbaname == null) {
      this.dbaname = new ArrayList<String>();
    }
    
    this.dbaname.add(dbanameItem);
    return this;
  }
  
  /**
  * Doing Business As Name
  * @return dbaname
  **/
  @ApiModelProperty(value = "Doing Business As Name")
  public List<String> getDbaname() {
    return dbaname;
  }
  public void setDbaname(List<String> dbaname) {
    this.dbaname = dbaname;
  }
  
  public ResponseValues visaStoreId(Integer visaStoreId) {
    this.visaStoreId = visaStoreId;
    return this;
  }

  
  /**
  * Visa Store Id for a Branch/Outlet
  * @return visaStoreId
  **/
  @ApiModelProperty(value = "Visa Store Id for a Branch/Outlet")
  public Integer getVisaStoreId() {
    return visaStoreId;
  }
  public void setVisaStoreId(Integer visaStoreId) {
    this.visaStoreId = visaStoreId;
  }
  
  public ResponseValues paymentFacilitatorName(List<String> paymentFacilitatorName) {
    this.paymentFacilitatorName = paymentFacilitatorName;
    return this;
  }

  public ResponseValues addPaymentFacilitatorNameItem(String paymentFacilitatorNameItem) {
    
    if (this.paymentFacilitatorName == null) {
      this.paymentFacilitatorName = new ArrayList<String>();
    }
    
    this.paymentFacilitatorName.add(paymentFacilitatorNameItem);
    return this;
  }
  
  /**
  * Payment Facilitator Name
  * @return paymentFacilitatorName
  **/
  @ApiModelProperty(value = "Payment Facilitator Name")
  public List<String> getPaymentFacilitatorName() {
    return paymentFacilitatorName;
  }
  public void setPaymentFacilitatorName(List<String> paymentFacilitatorName) {
    this.paymentFacilitatorName = paymentFacilitatorName;
  }
  
  public ResponseValues merchantUrl(List<String> merchantUrl) {
    this.merchantUrl = merchantUrl;
    return this;
  }

  public ResponseValues addMerchantUrlItem(String merchantUrlItem) {
    
    if (this.merchantUrl == null) {
      this.merchantUrl = new ArrayList<String>();
    }
    
    this.merchantUrl.add(merchantUrlItem);
    return this;
  }
  
  /**
  * URL of the Merchant
  * @return merchantUrl
  **/
  @ApiModelProperty(value = "URL of the Merchant")
  public List<String> getMerchantUrl() {
    return merchantUrl;
  }
  public void setMerchantUrl(List<String> merchantUrl) {
    this.merchantUrl = merchantUrl;
  }
  
  public ResponseValues locationAddressLongitude(String locationAddressLongitude) {
    this.locationAddressLongitude = locationAddressLongitude;
    return this;
  }

  
  /**
  * Merchant&amp;apos;s Location Adderess Longitude
  * @return locationAddressLongitude
  **/
  @ApiModelProperty(value = "Merchant&apos;s Location Adderess Longitude")
  public String getLocationAddressLongitude() {
    return locationAddressLongitude;
  }
  public void setLocationAddressLongitude(String locationAddressLongitude) {
    this.locationAddressLongitude = locationAddressLongitude;
  }
  
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseValues responseValues = (ResponseValues) o;
    return Objects.equals(this.locationAddressLatitude, responseValues.locationAddressLatitude) &&
        Objects.equals(this.merchantCity, responseValues.merchantCity) &&
        Objects.equals(this.merchantStreetAddress, responseValues.merchantStreetAddress) &&
        Objects.equals(this.merchantCategoryCode, responseValues.merchantCategoryCode) &&
        Objects.equals(this.distance, responseValues.distance) &&
        Objects.equals(this.visaEnterpriseName, responseValues.visaEnterpriseName) &&
        Objects.equals(this.businessLegalName, responseValues.businessLegalName) &&
        Objects.equals(this.visaStoreName, responseValues.visaStoreName) &&
        Objects.equals(this.visaMerchantId, responseValues.visaMerchantId) &&
        Objects.equals(this.merchantCategoryCodeDesc, responseValues.merchantCategoryCodeDesc) &&
        Objects.equals(this.merchantState, responseValues.merchantState) &&
        Objects.equals(this.visaMerchantName, responseValues.visaMerchantName) &&
        Objects.equals(this.merchantCountryCode, responseValues.merchantCountryCode) &&
        Objects.equals(this.merchantPostalCode, responseValues.merchantPostalCode) &&
        Objects.equals(this.dbaname, responseValues.dbaname) &&
        Objects.equals(this.visaStoreId, responseValues.visaStoreId) &&
        Objects.equals(this.paymentFacilitatorName, responseValues.paymentFacilitatorName) &&
        Objects.equals(this.merchantUrl, responseValues.merchantUrl) &&
        Objects.equals(this.locationAddressLongitude, responseValues.locationAddressLongitude);
  }

  @Override
  public int hashCode() {
    return Objects.hash(locationAddressLatitude, merchantCity, merchantStreetAddress, merchantCategoryCode, distance, visaEnterpriseName, businessLegalName, visaStoreName, visaMerchantId, merchantCategoryCodeDesc, merchantState, visaMerchantName, merchantCountryCode, merchantPostalCode, dbaname, visaStoreId, paymentFacilitatorName, merchantUrl, locationAddressLongitude);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseValues {\n");

    sb.append("    locationAddressLatitude: ").append(toIndentedString(locationAddressLatitude)).append("\n");
    sb.append("    merchantCity: ").append(toIndentedString(merchantCity)).append("\n");
    sb.append("    merchantStreetAddress: ").append(toIndentedString(merchantStreetAddress)).append("\n");
    sb.append("    merchantCategoryCode: ").append(toIndentedString(merchantCategoryCode)).append("\n");
    sb.append("    distance: ").append(toIndentedString(distance)).append("\n");
    sb.append("    visaEnterpriseName: ").append(toIndentedString(visaEnterpriseName)).append("\n");
    sb.append("    businessLegalName: ").append(toIndentedString(businessLegalName)).append("\n");
    sb.append("    visaStoreName: ").append(toIndentedString(visaStoreName)).append("\n");
    sb.append("    visaMerchantId: ").append(toIndentedString(visaMerchantId)).append("\n");
    sb.append("    merchantCategoryCodeDesc: ").append(toIndentedString(merchantCategoryCodeDesc)).append("\n");
    sb.append("    merchantState: ").append(toIndentedString(merchantState)).append("\n");
    sb.append("    visaMerchantName: ").append(toIndentedString(visaMerchantName)).append("\n");
    sb.append("    merchantCountryCode: ").append(toIndentedString(merchantCountryCode)).append("\n");
    sb.append("    merchantPostalCode: ").append(toIndentedString(merchantPostalCode)).append("\n");
    sb.append("    dbaname: ").append(toIndentedString(dbaname)).append("\n");
    sb.append("    visaStoreId: ").append(toIndentedString(visaStoreId)).append("\n");
    sb.append("    paymentFacilitatorName: ").append(toIndentedString(paymentFacilitatorName)).append("\n");
    sb.append("    merchantUrl: ").append(toIndentedString(merchantUrl)).append("\n");
    sb.append("    locationAddressLongitude: ").append(toIndentedString(locationAddressLongitude)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  
}



